use_frameworks!

target 'Aletheia_Example' do
  pod 'Aletheia', :path => '../'

  target 'Aletheia_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
